x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:

  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      mariadb: *healthy
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    environment:
      - MARIADB_HOST=mariadb

  dev:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    depends_on:
      mariadb: *healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MARIADB_HOST=mariadb
    command:
      - sleep
      - infinity

  mariadb:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: cecilia
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  js:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - npm
      - run
      - watch:js

  css:
    build:
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - npm
      - run
      - watch:css

volumes:
  database:
