x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:

  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    environment:
      - DB_HOST=mariadb

  test:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    depends_on:
      mariadb: *healthy
    command: bash -c "bundle exec rspec"
    deploy:
      restart_policy:
        condition: none
    environment:
      - RAILS_ENV=test
      - DB_HOST=mariadb

  mariadb:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: cecilia
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]


volumes:
  gem_cache:
  database:
