name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: database
          MARIADB_ROOT_PASSWORD: password
        ports: ["3306:3306"]
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run:  cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: run linting
        run: bundle exec standardrb
      - name: run tests
        run: bundle exec rspec
        env: 
          GHA_TEST: "true"
